# Generated by Django 5.1.5 on 2025-05-01 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farmlabs", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="type",
            new_name="device_type",
        ),
        migrations.RemoveField(
            model_name="warningthreshold",
            name="type",
        ),
        migrations.AddField(
            model_name="device",
            name="code",
            field=models.CharField(default=123, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="warningthreshold",
            name="warning_type",
            field=models.CharField(
                choices=[("high", "High"), ("low", "Low")],
                default="high",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("maintenance", "Maintenance"),
                ],
                default="online",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="warningthreshold",
            name="value",
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmlabs.farmlab",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="device",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="farmlabs.sector",
            ),
        ),
    ]
