# Generated by Django 5.1.5 on 2025-05-01 04:37

import datetime

import django.utils.timezone
from django.db import migrations

import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("farmlabs", "0003_rename_type_device_device_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="sector",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="warningthreshold",
            options={"get_latest_by": "modified"},
        ),
        migrations.AddField(
            model_name="device",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sector",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="warningthreshold",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025,
                    5,
                    1,
                    4,
                    37,
                    59,
                    128736,
                    tzinfo=datetime.UTC,
                ),
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="warningthreshold",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True,
                verbose_name="modified",
            ),
        ),
    ]
