# Generated by Django 5.1.5 on 2025-05-08 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farmlabs", "0005_devicetype_alter_device_device_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetype",
            name="color",
            field=models.CharField(default="#000000", max_length=7),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="farmlabs.devicetype",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="farmlabs.farmlab",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="farmlabs.sector",
            ),
        ),
        migrations.AlterField(
            model_name="farmlab",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farmlabs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sectors",
                to="farmlabs.farmlab",
            ),
        ),
        migrations.AlterField(
            model_name="warningthreshold",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warning_thresholds",
                to="farmlabs.device",
            ),
        ),
    ]
