# Generated by Django 5.1.5 on 2025-05-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "farmlabs",
            "0006_devicetype_color_alter_device_device_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="farmlab",
            name="token",
            field=models.CharField(
                blank=True,
                help_text="Unique token for farm lab.",
                max_length=255,
            ),
        ),
    ]
