# Generated by Django 5.1.5 on 2025-05-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farmlabs", "0007_farmlab_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmlab",
            name="token",
            field=models.CharField(
                blank=True,
                help_text="Unique token for farm lab.",
                max_length=1000,
            ),
        ),
    ]
