# Generated by Django 5.1.5 on 2025-05-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farmlabs", "0009_cultivationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cultivationlog",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("checking", "Kiểm tra"),
                    ("fertilizing", "Bón phân"),
                    ("hoeing", "Cày xới"),
                    ("planting", "Gieo trồng"),
                    ("prunning", "Tỉa cành"),
                    ("watering", "Tưới nước"),
                    ("weeding", "Nhổ cỏ"),
                ],
                default=None,
                max_length=15,
            ),
        ),
    ]
