name: "FarmLabWebPortal-backend"

services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -h postgres
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_DB=farmlab-dev
      - POSTGRES_USER=farmlab-user
      - POSTGRES_PASSWORD=farmlab
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
